/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiProfileRouteImport } from './routes/api/profile'
import { Route as ApiOrderRouteImport } from './routes/api/order'
import { Route as ApiLoginRouteImport } from './routes/api/login'
import { Route as ApiConnectBrokerRouteImport } from './routes/api/connect-broker'
import { Route as ApiBalanceRouteImport } from './routes/api/balance'
import { Route as ApiPricesSplatRouteImport } from './routes/api/prices.$'
import { Route as ApiAbSplatRouteImport } from './routes/api/ab.$'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileRoute = ApiProfileRouteImport.update({
  id: '/api/profile',
  path: '/api/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrderRoute = ApiOrderRouteImport.update({
  id: '/api/order',
  path: '/api/order',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLoginRoute = ApiLoginRouteImport.update({
  id: '/api/login',
  path: '/api/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConnectBrokerRoute = ApiConnectBrokerRouteImport.update({
  id: '/api/connect-broker',
  path: '/api/connect-broker',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBalanceRoute = ApiBalanceRouteImport.update({
  id: '/api/balance',
  path: '/api/balance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPricesSplatRoute = ApiPricesSplatRouteImport.update({
  id: '/api/prices/$',
  path: '/api/prices/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAbSplatRoute = ApiAbSplatRouteImport.update({
  id: '/api/ab/$',
  path: '/api/ab/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/api/balance': typeof ApiBalanceRoute
  '/api/connect-broker': typeof ApiConnectBrokerRoute
  '/api/login': typeof ApiLoginRoute
  '/api/order': typeof ApiOrderRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/ab/$': typeof ApiAbSplatRoute
  '/api/prices/$': typeof ApiPricesSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/api/balance': typeof ApiBalanceRoute
  '/api/connect-broker': typeof ApiConnectBrokerRoute
  '/api/login': typeof ApiLoginRoute
  '/api/order': typeof ApiOrderRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/ab/$': typeof ApiAbSplatRoute
  '/api/prices/$': typeof ApiPricesSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/api/balance': typeof ApiBalanceRoute
  '/api/connect-broker': typeof ApiConnectBrokerRoute
  '/api/login': typeof ApiLoginRoute
  '/api/order': typeof ApiOrderRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/ab/$': typeof ApiAbSplatRoute
  '/api/prices/$': typeof ApiPricesSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/api/balance'
    | '/api/connect-broker'
    | '/api/login'
    | '/api/order'
    | '/api/profile'
    | '/api/ab/$'
    | '/api/prices/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/api/balance'
    | '/api/connect-broker'
    | '/api/login'
    | '/api/order'
    | '/api/profile'
    | '/api/ab/$'
    | '/api/prices/$'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/api/balance'
    | '/api/connect-broker'
    | '/api/login'
    | '/api/order'
    | '/api/profile'
    | '/api/ab/$'
    | '/api/prices/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiBalanceRoute: typeof ApiBalanceRoute
  ApiConnectBrokerRoute: typeof ApiConnectBrokerRoute
  ApiLoginRoute: typeof ApiLoginRoute
  ApiOrderRoute: typeof ApiOrderRoute
  ApiProfileRoute: typeof ApiProfileRoute
  ApiAbSplatRoute: typeof ApiAbSplatRoute
  ApiPricesSplatRoute: typeof ApiPricesSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile': {
      id: '/api/profile'
      path: '/api/profile'
      fullPath: '/api/profile'
      preLoaderRoute: typeof ApiProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/order': {
      id: '/api/order'
      path: '/api/order'
      fullPath: '/api/order'
      preLoaderRoute: typeof ApiOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/login': {
      id: '/api/login'
      path: '/api/login'
      fullPath: '/api/login'
      preLoaderRoute: typeof ApiLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/connect-broker': {
      id: '/api/connect-broker'
      path: '/api/connect-broker'
      fullPath: '/api/connect-broker'
      preLoaderRoute: typeof ApiConnectBrokerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/balance': {
      id: '/api/balance'
      path: '/api/balance'
      fullPath: '/api/balance'
      preLoaderRoute: typeof ApiBalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/prices/$': {
      id: '/api/prices/$'
      path: '/api/prices/$'
      fullPath: '/api/prices/$'
      preLoaderRoute: typeof ApiPricesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ab/$': {
      id: '/api/ab/$'
      path: '/api/ab/$'
      fullPath: '/api/ab/$'
      preLoaderRoute: typeof ApiAbSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiBalanceRoute: ApiBalanceRoute,
  ApiConnectBrokerRoute: ApiConnectBrokerRoute,
  ApiLoginRoute: ApiLoginRoute,
  ApiOrderRoute: ApiOrderRoute,
  ApiProfileRoute: ApiProfileRoute,
  ApiAbSplatRoute: ApiAbSplatRoute,
  ApiPricesSplatRoute: ApiPricesSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
