/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiProfileRouteImport } from './routes/api/profile'
import { Route as ApiOrderRouteImport } from './routes/api/order'
import { Route as ApiLoginRouteImport } from './routes/api/login'
import { Route as ApiBalanceRouteImport } from './routes/api/balance'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileRoute = ApiProfileRouteImport.update({
  id: '/api/profile',
  path: '/api/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrderRoute = ApiOrderRouteImport.update({
  id: '/api/order',
  path: '/api/order',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLoginRoute = ApiLoginRouteImport.update({
  id: '/api/login',
  path: '/api/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBalanceRoute = ApiBalanceRouteImport.update({
  id: '/api/balance',
  path: '/api/balance',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/balance': typeof ApiBalanceRoute
  '/api/login': typeof ApiLoginRoute
  '/api/order': typeof ApiOrderRoute
  '/api/profile': typeof ApiProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/balance': typeof ApiBalanceRoute
  '/api/login': typeof ApiLoginRoute
  '/api/order': typeof ApiOrderRoute
  '/api/profile': typeof ApiProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/balance': typeof ApiBalanceRoute
  '/api/login': typeof ApiLoginRoute
  '/api/order': typeof ApiOrderRoute
  '/api/profile': typeof ApiProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/balance' | '/api/login' | '/api/order' | '/api/profile'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/balance' | '/api/login' | '/api/order' | '/api/profile'
  id:
    | '__root__'
    | '/'
    | '/api/balance'
    | '/api/login'
    | '/api/order'
    | '/api/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiBalanceRoute: typeof ApiBalanceRoute
  ApiLoginRoute: typeof ApiLoginRoute
  ApiOrderRoute: typeof ApiOrderRoute
  ApiProfileRoute: typeof ApiProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile': {
      id: '/api/profile'
      path: '/api/profile'
      fullPath: '/api/profile'
      preLoaderRoute: typeof ApiProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/order': {
      id: '/api/order'
      path: '/api/order'
      fullPath: '/api/order'
      preLoaderRoute: typeof ApiOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/login': {
      id: '/api/login'
      path: '/api/login'
      fullPath: '/api/login'
      preLoaderRoute: typeof ApiLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/balance': {
      id: '/api/balance'
      path: '/api/balance'
      fullPath: '/api/balance'
      preLoaderRoute: typeof ApiBalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiBalanceRoute: ApiBalanceRoute,
  ApiLoginRoute: ApiLoginRoute,
  ApiOrderRoute: ApiOrderRoute,
  ApiProfileRoute: ApiProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
